variable "rgs" {}
variable "virtual_networks" {}
variable "subnets" {}
variable "nic" {}
variable "vm" {}
variable "db_server_name" {}
variable "resource_group_name" {}
variable "location" {}
variable "db" {}